# apiVersion: v1
# kind: Pod
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  containers:
    - name: elasticsearch
      image: selesabraham/elasticsearch:latest
      ports:
        - containerPort: 8080
      command: ["/bin/sh"]
      args: ["-c", "sleep 500 && echo Sleep expired > /dev/termination-log"]
