apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch
  labels:
    app: elastcisearch
spec:
  containers:
    - name: elasticsearch
      image: selesabraham/elasticsearchimage:61
      ports:
        - containerPort: 8080