apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  labels:
    kube-monkey/enabled: "enabled"
    kube-monkey/identifier: "deployment-name"
    kube-monkey/mtbf: '2'
    kube-monkey/kill-mode: "fixed"
    kube-monkey/kill-value: "1"
  version: 7.5.1
  nodeSets:
  - name: default
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
  containers:
    - name: elasticsearch
      image: selesabraham/elasticsearch:latest
      ports:
        - containerPort: 8080
      command: ["/bin/sh"]
      args: ["-c", "sleep 500 && echo Sleep expired > /dev/termination-log"]
      envFrom:
        - configMapRef:
            name: elasticsearch-configmap
      readinessProbe:
       httpGet:
         path: /
         port: 8080
       timeoutSeconds: 2