kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
  - protocol: TCP
    nodePort: 32444
    port: 8080
    targetPort: 8080
  type: NodePort
  