kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
spec:
  replicas: 2
  selector:
    app: elasticsearchcontainer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  type: LoadBalancer  
  